// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int? PatientId { get; set; }

    public int? ServiceId { get; set; }

    public int? PaymentId { get; set; }

    public int? DoctorId { get; set; }

    public int? SlotId { get; set; }

    public DateTime? DateBooking { get; set; }

    public string Description { get; set; }

    public DateTime? CreateAt { get; set; }

    public string Note { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual Examination Examination { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual Service Service { get; set; }

    public virtual Slot Slot { get; set; }
}