// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Infertility_Treatment_Managements.Models;
using System;
using System.Collections.Generic;

namespace Infertility_Treatment_Managements.Models;

public partial class Doctor
{
    public int DoctorId { get; set; }
    
    public int? UserId { get; set; }

    public string DoctorName { get; set; }

    public string Specialization { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<TreatmentPlan> TreatmentPlans { get; set; } = new List<TreatmentPlan>();

    public virtual User User { get; set; }
}