// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Doctor
{
    public int DoctorId { get; set; }
    
    public int? UserId { get; set; }  // Add this line to include UserId

    public string DoctorName { get; set; }

    public string Specialization { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual User User { get; set; }  // Rename from DoctorNavigation to User for consistency
}