// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Examination
{
    public int ExaminationId { get; set; }

    public int? BookingId { get; set; }

    public DateTime? ExaminationDate { get; set; }

    public string ExaminationDescription { get; set; }

    public string Status { get; set; }

    public string Result { get; set; }

    public DateTime? CreateAt { get; set; }

    public string Note { get; set; }

    public virtual Booking Booking { get; set; }
}