// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Patient
{
    public int PatientId { get; set; }

    public int? UserId { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Address { get; set; }

    public string Gender { get; set; }

    public string BloodType { get; set; }

    public string EmergencyPhoneNumber { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual ICollection<PatientDetail> PatientDetails { get; set; } = new List<PatientDetail>();

    public virtual User User { get; set; }
}