// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class PatientDetail
{
    public int PatientDetailId { get; set; }

    public int? PatientId { get; set; }

    public string TreatmentStatus { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual ICollection<TreatmentProcess> TreatmentProcess { get; set; } = new List<TreatmentProcess>();
}