// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Infertility_Treatment_Managements.Models;
using System;
using System.Collections.Generic;

namespace Infertility_Treatment_Managements.Models;

public partial class PatientDetail
{
    public string PatientDetailId { get; set; }

    public string? PatientId { get; set; }

    public string TreatmentStatus { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual ICollection<TreatmentProcess> TreatmentProcessesFk { get; set; } = new List<TreatmentProcess>();

    public virtual ICollection<TreatmentPlan> TreatmentPlansFk { get; set; } = new List<TreatmentPlan>();
}