// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infertility_Treatment_Managements.Models;

public partial class Payment
{
    public string PaymentId { get; set; }

    public string? BookingId { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Status { get; set; }

    public string Method { get; set; }

    public virtual Booking Booking { get; set; }
}