// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infertility_Treatment_Managements.Models;

public partial class Service
{
    public string ServiceId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public decimal? Price { get; set; }
    public string Status { get; set; }
    
    public virtual ICollection<Booking> BookingsFk { get; set; } = new List<Booking>();
}