// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infertility_Treatment_Managements.Models;

public partial class Slot
{
    public string SlotId { get; set; }

    public string SlotName { get; set; }

    public string StartTime { get; set; }

    public string EndTime { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}