// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Infertility_Treatment_Managements.Models;
using System;
using System.Collections.Generic;

namespace Infertility_Treatment_Managements.Models;

public partial class TreatmentProcess
{
    public string TreatmentProcessId { get; set; }
    public string Method { get; set; }
    public string? PatientDetailId { get; set; }
    public string? TreatmentPlanId { get; set; }
    public DateTime? ScheduledDate { get; set; }
    public DateTime? ActualDate { get; set; }
    public string Result { get; set; }
    public string Status { get; set; }
    
    public virtual PatientDetail PatientDetail { get; set; }
    public virtual TreatmentPlan TreatmentPlan { get; set; }
}