// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class TreatmentProcess
{
    public int TreatmentProcessId { get; set; }

    public string Method { get; set; }

    public int? PatientDetailId { get; set; }

    public DateOnly? ScheduledDate { get; set; }

    public DateOnly? ActualDate { get; set; }

    public string Result { get; set; }

    public string Status { get; set; }

    public virtual PatientDetail PatientDetail { get; set; }
}